export const assets = {
  digitalOceanIcon: '/programming/digital-ocean-icon.svg',
  figmaIcon: '/programming/figma.svg',
  gitIcon: '/programming/git-icon.svg',
  githubOctocatIcon: '/programming/github-octocat.svg',
  headlessuiIcon: '/programming/headlessui.svg',
  javascriptIcon: '/programming/javascript.svg',
  microsoftAzureIcon: '/programming/microsoft-azure.svg',
  mongodbIcon: '/programming/mongodb-icon.svg',
  mysqlIcon: '/programming/mysql.svg',
  nextjsIcon: '/programming/nextjs-icon.svg',
  nodejsIcon: '/programming/nodejs-icon.svg',
  postgresqlIcon: '/programming/postgresql.svg',
  pythonIcon: '/programming/python.svg',
  reactQueryIcon: '/programming/react-query-icon.svg',
  reactIcon: '/programming/react.svg',
  sqliteIcon: '/programming/sqlite.svg',
  tailwindcssIcon: '/programming/tailwindcss-icon.svg',
  typescriptIcon: '/programming/typescript-icon.svg',
  ubuntuIcon: '/programming/ubuntu.svg',
  vercelIcon: '/programming/vercel-icon.svg',
};
